version: 1

env:
    GO111MODULE: on
    CGO_ENABLED: "0" # It's advisable to wrap numeric values in quotes to ensure they're interpreted as strings.

flags:
    - "-trimpath"
    - "-tags=netgo"

goos:
    - windows
    - linux
    - darwin

goarch:
    - amd64
    - arm64

binary: binary-{{ .Os }}-{{ .Arch }}

ldflags:
    - "-X main.Version={{ .Env.VERSION }}"
    - "-X main.Commit={{ .Env.COMMIT }}"
    - "-X main.CommitDate={{ .Env.COMMIT_DATE }}"
    - "-X main.TreeState={{ .Env.TREE_STATE }}"
