version: 1

env:
    - GO111MODULE=on
    - CGO_ENABLED=0

flags:
    - -trimpath
    - -tags=netgo

goos:
    - windows
    - linux
    - darwin
goarch:
    - amd64
    - arm64

# Binary output name.
# {{ .Os }} will be replaced by goos field in the config file.
# {{ .Arch }} will be replaced by goarch field in the config file.
binary: binary-{{ .Os }}-{{ .Arch }}

# (Optional) ldflags generated dynamically in the workflow, and set as the `evaluated-envs` input variables in the workflow.
ldflags:
    - "-X main.Version={{ .Env.VERSION }}"
    - "-X main.Commit={{ .Env.COMMIT }}"
    - "-X main.CommitDate={{ .Env.COMMIT_DATE }}"
    - "-X main.TreeState={{ .Env.TREE_STATE }}"
